### ISSUE TITLE
It does not work with NodePort configuration (localhost:3000 is hardcoded)

### ISSUE THREAD

**Issue by marcosdiez** [spekt8/spekt8#10]
Because of network and firewall and other reasons, I can't just do 
`kubectl port-forward deployment/spekt8 3000:3000`

Instead I had to install it using NodePort.

Now spekt8 shows me a blank screen for it tries to access `localhost:3000` instead of THE_IP_ADDRESS:THE_PORT  (i.e. this `localhost:3000` is harcoded)

below are the YAML settings I used to install it:
```


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spekt8
spec:
  selector:
    matchLabels:
      k8s-app: spekt8
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: spekt8
    spec:
      containers:
        - name: spekt8
          image: elliotxkim/spekt8
          ports:
            - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: spekt8
  labels:
    k8s-app: spekt8
spec:
  ports:
  - protocol: TCP
    port: 3000
  type: NodePort
  selector:
    k8s-app: spekt8
```
