### ISSUE TITLE
namespace hardcoded to default

### ISSUE THREAD

**Issue by xchapter7x** [spekt8/spekt8#11]
it seems like the namespace is hardcoded to `default`
Can this be made to be configurable?
Perhaps a dropdown in the UI or via a ENV Var for the pod.

thanks.

ie
https://github.com/spekt8/spekt8/blob/master/src/server/express-app.js#L49

**Comment by caiohaz** [comment]
+1

**Comment by chaosdudu** [comment]
+1 when I deploy with different namespace, I can not access to the cluster info

**Comment by tprakash17** [comment]
+1

**Comment by sfxworks** [comment]
Please do this

**Comment by mickoallen** [comment]
+1

**Comment by geerlingguy** [comment]
Also unless I'm reading it wrong, wouldn't this RBAC CRB (https://github.com/spekt8/spekt8/blob/master/fabric8-rbac.yaml#L12) allow full access to any pod, not just the spekt8 one?

**Comment by bitsofinfo** [comment]
+1 this is a dealbreaker to even eval this. I can't see any information for stuff in any namespace outside of `default`

**Comment by mickoallen** [comment]
> +1 this is a dealbreaker to even eval this. I can't see any information for stuff in any namespace outside of `default`

it is pretty simple to fork and add another namespace at least to check it out, only took a couple of minutes.

**Comment by Claywd** [comment]
@mickoallen Can you push the changes you made back to your fork so we can see how you did this?

**Comment by Claywd** [comment]
For anyone curious. I forked the repo, adjsuted the namespace value in k8sApi*.listNamespace* and replaced the vauld 'default' with 'mynamespace'. Built, deployed, but no go. I have less errors overall but this one I'm not sure how to handle. 

console.error('SBO Downloader is unable to download the course, it is out of control issue.');

**Comment by mickoallen** [comment]
> @mickoallen Can you push the changes you made back to your fork so we can see how you did this?

Sure, i fully cheesed it though, don't know how useful it is.
Shouldn't be hard to make it more configurable.

 https://github.com/spekt8/spekt8/compare/master...mickoallen:master

**Comment by Claywd** [comment]
@mickoallen dang... I dd exactly what you did already and I'm still getting that same error. Does it actually work for you? did you make any changes to the rbac?

**Comment by mickoallen** [comment]
@Claywd damn, i didn't make any changes there. Also if i remember correctly i only used it against minikube...

**Comment by Claywd** [comment]
@mickoallen hmm.. I mean I am using it against AKS but its hard to believe that would make a difference when all the permissions are already setup. @cbanigan might take a look for us soon. Hopefully he can see what I'm missing.

**Comment by jharris-tc** [comment]
+1 to this, also having this problem

**Comment by nsisodiya** [comment]
+1

**Comment by cvernooy23** [comment]
+1 same issue. Doesn't seem like author is going to address this

**Comment by robZrad** [comment]
+1

**Comment by korjavin** [comment]
+1

**Comment by sanarena** [comment]
I have [forked the code](https://github.com/sanarena/spekt8) and make namespace modifiable via environment value, you just have to pass **NAMESPACE** as env value and using **sanarena/spekt8** as image url.

As an example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spekt8
spec:
  selector:
    matchLabels:
      component: spekt8
  replicas: 1
  template:
    metadata:
      labels:
        component: spekt8
    spec:
      containers:
        - name: spekt8
          image: sanarena/spekt8
          ports:
            - containerPort: 3000
          env:
          - name: NAMESPACE
            value: sanarena
```
