### ISSUE TITLE
Ingress-rules not displayed (just the default host)

### ISSUE THREAD

**Issue by stefan2904** [spekt8/spekt8#14]
I have the following Ingress configuration (which is working):

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress1
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - nginx-ingress1.example.com
    - nginx-ingress2.example.com
    secretName: letsencrypt-prod
  backend:
    serviceName: nginx-example1
    servicePort: 80
  rules:
  - host: nginx-ingress1.example.com
    http:
      paths: 
      - path: /
        backend:
          serviceName: nginx-example1
          servicePort: 80
  - host: nginx-ingress2.example.com
    http:
      paths: 
      - path: /
        backend:
          serviceName: nginx-example2
          servicePort: 80

```

So there are two hosts (mapped to two services) plus a default host (mapped to one of the services).

Unfortunately spekt8 only renders the default host:

![selection_768](https://user-images.githubusercontent.com/527767/52892094-bc416f00-318f-11e9-9755-94f2c347a14d.png)

My expectation is that this Ingress is supposed to point at both services.

---

_(I am new to kubernetes, so I am not sure if I used the correct terms for the mentioned concepts, e.g. "Ingress rule" and "default host".)_
