### ISSUE TITLE
Service/Pod connection broken when selector contain multiple labels

### ISSUE THREAD

**Issue by ClementGautier** [spekt8/spekt8#22]
My services uses multiple labels to target their pods (like many helm chart):
```
spec:
  selector:
    app: my-app
    release: my-release
```

Unfortunately the fetch.js only test the first label: https://github.com/spekt8/spekt8/blob/0cdca49bb8adc0e0c3b736f64239f6d305a717f5/src/client/supplement/fetch.js#L160

It looks like this repository is not actively maintained but in case a maintainer comes by...
